# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Slope_Stability_Analysis
                                 A QGIS plugin
 This Plugin is for slope stability analysis using Bishop's Simplified Method  with Monte Carlo Simulation
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-07
        copyright            : (C) 2026 by M. Abdul Malik Nainggolan
        email                : abdulmaliknainggolan2@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Slope_Stability_Analysis class from file Slope_Stability_Analysis.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Slope_Stability_Analysis import Slope_Stability_Analysis
    return Slope_Stability_Analysis(iface)
